"""cascade_delete_documents_on_project

Revision ID: 2609cab55521
Revises: dc9d0bee3af6
Create Date: 2026-06-01 21:18:22.045045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2609cab55521'
down_revision: Union[str, Sequence[str], None] = 'dc9d0bee3af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_project_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_project_id_fkey'), 'documents', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
