"""add_project_id_to_plans

Revision ID: 3ae184b367ec
Revises: 2609cab55521
Create Date: 2026-06-01 21:49:49.545788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae184b367ec'
down_revision: Union[str, Sequence[str], None] = '2609cab55521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_foreign_key(None, 'plans', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_column('plans', 'project_id')
    # ### end Alembic commands ###
