"""add_uuid_to_all_models

Revision ID: 5cff594d9759
Revises: e5f6a7b8c9d0
Create Date: 2026-06-01 20:26:03.000786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cff594d9759'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_comments_uuid'), 'comments', ['uuid'], unique=True)
    op.add_column('conversations', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_conversations_uuid'), 'conversations', ['uuid'], unique=True)
    op.drop_index(op.f('ix_document_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('documents', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_documents_uuid'), 'documents', ['uuid'], unique=True)
    op.add_column('invitations', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('invitations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_invitations_token'), 'invitations', type_='unique')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_invited_by_id'), 'invitations', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_invitations_uuid'), 'invitations', ['uuid'], unique=True)
    op.add_column('memories', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_memories_uuid'), 'memories', ['uuid'], unique=True)
    op.add_column('messages', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_messages_uuid'), 'messages', ['uuid'], unique=True)
    op.add_column('plan_steps', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_plan_steps_uuid'), 'plan_steps', ['uuid'], unique=True)
    op.add_column('plans', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_plans_uuid'), 'plans', ['uuid'], unique=True)
    op.add_column('projects', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_projects_created_by_id'), 'projects', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=True)
    op.add_column('tasks', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_tasks_uuid'), 'tasks', ['uuid'], unique=True)
    op.add_column('users', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.add_column('workspace_members', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('workspace_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workspace_members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('ix_workspace_members_workspace_user'), 'workspace_members', type_='unique')
    op.create_index('ix_workspace_members_workspace_user', 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_workspace_members_uuid'), 'workspace_members', ['uuid'], unique=True)
    op.add_column('workspaces', sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_workspaces_uuid'), 'workspaces', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_uuid'), table_name='workspaces')
    op.drop_column('workspaces', 'uuid')
    op.drop_index(op.f('ix_workspace_members_uuid'), table_name='workspace_members')
    op.drop_index('ix_workspace_members_workspace_user', table_name='workspace_members')
    op.create_unique_constraint(op.f('ix_workspace_members_workspace_user'), 'workspace_members', ['workspace_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('workspace_members', 'updated_at')
    op.drop_column('workspace_members', 'created_at')
    op.drop_column('workspace_members', 'uuid')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_tasks_uuid'), table_name='tasks')
    op.drop_column('tasks', 'uuid')
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_id'), table_name='projects')
    op.drop_column('projects', 'uuid')
    op.drop_index(op.f('ix_plans_uuid'), table_name='plans')
    op.drop_column('plans', 'uuid')
    op.drop_index(op.f('ix_plan_steps_uuid'), table_name='plan_steps')
    op.drop_column('plan_steps', 'uuid')
    op.drop_index(op.f('ix_messages_uuid'), table_name='messages')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'uuid')
    op.drop_index(op.f('ix_memories_uuid'), table_name='memories')
    op.drop_column('memories', 'uuid')
    op.drop_index(op.f('ix_invitations_uuid'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invited_by_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=False)
    op.create_unique_constraint(op.f('uq_invitations_token'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('invitations', 'updated_at')
    op.drop_column('invitations', 'uuid')
    op.drop_index(op.f('ix_documents_uuid'), table_name='documents')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'uuid')
    op.create_index(op.f('ix_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_conversations_uuid'), table_name='conversations')
    op.drop_column('conversations', 'uuid')
    op.drop_index(op.f('ix_comments_uuid'), table_name='comments')
    op.drop_column('comments', 'uuid')
    # ### end Alembic commands ###
