"""add_plans_and_plan_steps

Revision ID: a7972d379712
Revises: a1b2c3d4e5f7
Create Date: 2026-06-03 10:41:25.339168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7972d379712'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Remove orphan plans (null project_id) left over from previous implementation
    op.execute("DELETE FROM plan_steps WHERE plan_id IN (SELECT id FROM plans WHERE project_id IS NULL)")
    op.execute("DELETE FROM plans WHERE project_id IS NULL")

    op.alter_column('plan_steps', 'dependencies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('plan_steps_linked_task_id_fkey'), 'plan_steps', type_='foreignkey')
    op.drop_constraint(op.f('plan_steps_plan_id_fkey'), 'plan_steps', type_='foreignkey')
    op.create_foreign_key(None, 'plan_steps', 'tasks', ['linked_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'plan_steps', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plans', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('plans_user_id_fkey'), 'plans', type_='foreignkey')
    op.drop_constraint(op.f('plans_workspace_id_fkey'), 'plans', type_='foreignkey')
    op.create_foreign_key(None, 'plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('plans', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.create_foreign_key(op.f('plans_workspace_id_fkey'), 'plans', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('plans_user_id_fkey'), 'plans', 'users', ['user_id'], ['id'])
    op.alter_column('plans', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'plan_steps', type_='foreignkey')
    op.drop_constraint(None, 'plan_steps', type_='foreignkey')
    op.create_foreign_key(op.f('plan_steps_plan_id_fkey'), 'plan_steps', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(op.f('plan_steps_linked_task_id_fkey'), 'plan_steps', 'tasks', ['linked_task_id'], ['id'])
    op.alter_column('plan_steps', 'dependencies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
