"""add_project_id_to_documents

Revision ID: dc9d0bee3af6
Revises: 5cff594d9759
Create Date: 2026-06-01 21:07:32.793814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9d0bee3af6'
down_revision: Union[str, Sequence[str], None] = '5cff594d9759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_column('documents', 'project_id')
    # ### end Alembic commands ###
